insert into public.materials_tools_suppliers (
  id,
  name,
  nation,
  region,
  verified,
  verification_tier,
  avatar,
  cover,
  specialties,
  bio,
  response_time,
  fulfillment_score
)
values
  (
    'sup-1',
    'Red Ochre Materials Collective',
    'Pitjantjatjara',
    'Central Australia',
    true,
    'platinum',
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1400&h=700&fit=crop',
    array['Ochre pigments', 'Carving stone', 'Harvest protocol'],
    'Community-run materials source supplying ochres, stone, and harvested earth pigments with full provenance records.',
    'Responds in under 8 hours',
    98
  ),
  (
    'sup-2',
    'Awa Fibre House',
    'Maori',
    'Waikato, Aotearoa',
    true,
    'gold',
    'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1494526585095-c41746248156?w=1400&h=700&fit=crop',
    array['Flax fibres', 'Weaving tools', 'Natural dyes'],
    'Supplier network for fibres, weaving tools, and dye preparations grounded in community fibre practice.',
    'Responds in 1 business day',
    95
  ),
  (
    'sup-3',
    'Prairie Bead & Hide Exchange',
    'Lakota',
    'South Dakota, US',
    true,
    'gold',
    'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1400&h=700&fit=crop',
    array['Brain-tanned hides', 'Bead packs', 'Regalia findings'],
    'Artist-to-artist supplier specializing in beadwork inputs, hide preparation, and small-batch regalia materials.',
    'Responds in under 12 hours',
    93
  ),
  (
    'sup-4',
    'Coastal Tool Library Network',
    'Haida',
    'British Columbia, Canada',
    true,
    'silver',
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1400&h=700&fit=crop',
    array['Tool rental', 'Repair services', 'Studio equipment'],
    'Shared equipment and maker support hubs giving artists access to expensive tools without full ownership costs.',
    'Responds in 1-2 business days',
    91
  )
on conflict (id) do update set
  name = excluded.name,
  nation = excluded.nation,
  region = excluded.region,
  verified = excluded.verified,
  verification_tier = excluded.verification_tier,
  avatar = excluded.avatar,
  cover = excluded.cover,
  specialties = excluded.specialties,
  bio = excluded.bio,
  response_time = excluded.response_time,
  fulfillment_score = excluded.fulfillment_score;

insert into public.materials_tools_listings (
  id,
  supplier_id,
  title,
  supplier_name,
  nation,
  category,
  kind,
  price,
  currency,
  image,
  stock_label,
  lead_time,
  verified,
  verification_tier,
  summary,
  traceability,
  certifications,
  moq_label
)
values
  (
    'mt-101',
    'sup-1',
    'Ceremonial Ochre Pigment Set',
    'Red Ochre Materials Collective',
    'Pitjantjatjara',
    'natural-pigments-dyes',
    'material',
    42,
    'USD',
    'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=1200&h=900&fit=crop',
    'In Stock',
    'Ships in 3-5 days',
    true,
    'platinum',
    'Three natural ochre pigments with harvest story, safety notes, and mixing guidance.',
    '{"originRegion":"Mimili Ridge Country","harvestDate":"2026-02-08","method":"Low-impact hand harvest under community permit","qrLabel":"Scan origin story"}'::jsonb,
    array['Community Verified', 'Low-impact Harvest'],
    'MOQ 1 set'
  ),
  (
    'mt-102',
    'sup-2',
    'Harakeke Fibre Preparation Bundle',
    'Awa Fibre House',
    'Maori',
    'fibers-textile-materials',
    'material',
    58,
    'USD',
    'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=1200&h=900&fit=crop',
    'Limited',
    'Ships in 7 days',
    true,
    'gold',
    'Prepared flax fibre bundle with cutting protocol notes and dye pairing guide.',
    '{"originRegion":"Waikato Wetland Gardens","harvestDate":"2026-01-28","method":"Selective blade harvest with rotational replanting","qrLabel":"Scan harvester profile"}'::jsonb,
    array['Kaitiakitanga Certified', 'Community Verified'],
    'MOQ 5 bundles'
  ),
  (
    'mt-103',
    'sup-3',
    'Brain-Tanned Hide Panel',
    'Prairie Bead & Hide Exchange',
    'Lakota',
    'hides-feathers-quills',
    'material',
    145,
    'USD',
    'https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=1200&h=900&fit=crop',
    'Small Batch',
    'Ships in 5-8 days',
    true,
    'gold',
    'Soft-finished hide panel suitable for regalia, quillwork, and cultural crafts.',
    '{"originRegion":"Prairie Plains Cooperative Range","harvestDate":"2026-02-02","method":"Ethical sourcing + brain tan + smoke finish","qrLabel":"Scan tanning log"}'::jsonb,
    array['Ethical Sourcing', 'Traditional Tanning'],
    'MOQ 1 panel'
  ),
  (
    'mt-104',
    'sup-1',
    'Soapstone Carving Block Pack',
    'Red Ochre Materials Collective',
    'Pitjantjatjara',
    'woods-carving-materials',
    'material',
    64,
    'USD',
    'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&h=900&fit=crop',
    'In Stock',
    'Ships in 4 days',
    true,
    'platinum',
    'Small-format carving blocks selected for education programs and fine carving practice.',
    '{"originRegion":"Anangu Quarry Line","harvestDate":"2026-01-18","method":"Community-managed extraction and shaping","qrLabel":"Scan quarry record"}'::jsonb,
    array['Traceable Quarry', 'Community Verified'],
    'MOQ 3 blocks'
  ),
  (
    'mt-105',
    'sup-3',
    'Regalia Bead Spectrum Kit',
    'Prairie Bead & Hide Exchange',
    'Lakota',
    'beads-findings',
    'bulk-supply',
    33,
    'USD',
    'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=1200&h=900&fit=crop',
    'In Stock',
    'Ships in 2-4 days',
    true,
    'gold',
    'Curated seed bead colourway pack with shell discs and pattern planning cards.',
    '{"originRegion":"Prairie Bead Studio","harvestDate":"2026-02-10","method":"Studio-packed supply bundle","qrLabel":"Scan packing notes"}'::jsonb,
    array['Artist Packed', 'Community Verified'],
    'MOQ 10 kits'
  ),
  (
    'mt-106',
    'sup-2',
    'Backstrap Loom Starter Set',
    'Awa Fibre House',
    'Maori',
    'textile-weaving-tools',
    'tool',
    210,
    'USD',
    'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=1200&h=900&fit=crop',
    'Made to Order',
    'Ships in 12 days',
    true,
    'gold',
    'Compact loom set with weaving sword, heddles, setup guide, and maintenance notes.',
    '{"originRegion":"Waikato Workshop Bench","harvestDate":"2026-02-05","method":"Built by community tool makers","qrLabel":"Scan maker notes"}'::jsonb,
    array['Community Built', 'Workshop Ready'],
    'MOQ 1 loom set'
  )
on conflict (id) do update set
  supplier_id = excluded.supplier_id,
  title = excluded.title,
  supplier_name = excluded.supplier_name,
  nation = excluded.nation,
  category = excluded.category,
  kind = excluded.kind,
  price = excluded.price,
  currency = excluded.currency,
  image = excluded.image,
  stock_label = excluded.stock_label,
  lead_time = excluded.lead_time,
  verified = excluded.verified,
  verification_tier = excluded.verification_tier,
  summary = excluded.summary,
  traceability = excluded.traceability,
  certifications = excluded.certifications,
  moq_label = excluded.moq_label;

insert into public.materials_tools_rentals (
  id,
  title,
  hub_name,
  nation,
  location,
  daily_rate_label,
  image,
  summary,
  availability,
  equipment_type
)
values
  (
    'rental-1',
    'Community Kiln Access Pass',
    'Coastal Tool Library Network',
    'Haida',
    'Prince Rupert, BC',
    '$48 / firing slot',
    'https://images.unsplash.com/photo-1517685352821-92cf88aee5a5?w=1200&h=900&fit=crop',
    'Book kiln time with glazing bench access, loading support, and safety orientation.',
    'Open next 14 days',
    'Ceramics'
  ),
  (
    'rental-2',
    'Flex Shaft Jewelry Bench Bundle',
    'Prairie Bead & Hide Exchange',
    'Lakota',
    'Rapid City, SD',
    '$35 / day',
    'https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=1200&h=900&fit=crop',
    'Bench station with flex shaft, forming tools, torch space, and shared solder setup.',
    'Booked weekends',
    'Jewelry'
  ),
  (
    'rental-3',
    'Large-format Scanner + Photo Tent',
    'Coastal Tool Library Network',
    'Haida',
    'Prince Rupert, BC',
    '$60 / day',
    'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&h=900&fit=crop',
    'Shared digitization rig for portfolios, archives, cataloguing, and print prep.',
    'Reserve 5 days ahead',
    'Digital'
  )
on conflict (id) do update set
  title = excluded.title,
  hub_name = excluded.hub_name,
  nation = excluded.nation,
  location = excluded.location,
  daily_rate_label = excluded.daily_rate_label,
  image = excluded.image,
  summary = excluded.summary,
  availability = excluded.availability,
  equipment_type = excluded.equipment_type;

insert into public.materials_tools_services (
  id,
  title,
  provider,
  nation,
  rate_label,
  image,
  summary,
  service_type
)
values
  (
    'svc-1',
    'Equipment Repair & Maintenance',
    'Coastal Tool Library Network',
    'Haida',
    '$95/hr',
    'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1200&h=900&fit=crop',
    'Repair for looms, carving tools, flex shafts, and studio gear with parts sourcing support.',
    'repair'
  ),
  (
    'svc-2',
    'Material Sourcing Consultation',
    'Red Ochre Materials Collective',
    'Pitjantjatjara',
    '$140/session',
    'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&h=900&fit=crop',
    'Get sourcing help for pigments, carving materials, and culturally appropriate substitutions.',
    'sourcing'
  ),
  (
    'svc-3',
    'Bulk Buying Co-op Facilitation',
    'Awa Fibre House',
    'Maori',
    '2% co-op admin',
    'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&h=900&fit=crop',
    'Coordinate group orders, supplier matching, and consolidated freight for artist cohorts.',
    'co-op'
  ),
  (
    'svc-4',
    'Surplus Materials Brokerage',
    'Prairie Bead & Hide Exchange',
    'Lakota',
    '$20 listing fee',
    'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&h=900&fit=crop',
    'Help artists re-home surplus stock, studio equipment, and unopened supply runs.',
    'surplus'
  )
on conflict (id) do update set
  title = excluded.title,
  provider = excluded.provider,
  nation = excluded.nation,
  rate_label = excluded.rate_label,
  image = excluded.image,
  summary = excluded.summary,
  service_type = excluded.service_type;

insert into public.materials_tools_coop_orders (
  id,
  title,
  summary,
  target_units,
  committed_units,
  close_date,
  image,
  preferred_category
)
values
  (
    'coop-1',
    'Bulk Seed Bead Colorway Run',
    'Collective order for beadwork studios seeking shared discounts on regalia palettes.',
    120,
    84,
    '2026-04-02',
    'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=1200&h=900&fit=crop',
    'beads-findings'
  ),
  (
    'coop-2',
    'Shared Loom Hardware Refill',
    'Regional co-op for heddles, beams, tie cords, and textile tool replacement parts.',
    80,
    37,
    '2026-03-28',
    'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=1200&h=900&fit=crop',
    'textile-weaving-tools'
  ),
  (
    'coop-3',
    'Archival Shipping Material Pool',
    'Joint order for crates, tubes, foam inserts, and labels for gallery season.',
    200,
    142,
    '2026-04-11',
    'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&h=900&fit=crop',
    'packaging-shipping-supplies'
  )
on conflict (id) do update set
  title = excluded.title,
  summary = excluded.summary,
  target_units = excluded.target_units,
  committed_units = excluded.committed_units,
  close_date = excluded.close_date,
  image = excluded.image,
  preferred_category = excluded.preferred_category;
